# -*- coding: utf-8 -*-
"""CN_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dX_pHvAArgSHtHTovS0DbBXB498Ciwl0
"""

import numpy as np
import random
import pandas as pd
import time
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List, Dict, Tuple

# ----------------- 1. ENVIRONMENT & MODEL DEFINITIONS -----------------

# Heterogeneous Edge Servers (Realistic Setup)
SERVERS = [
    {"id": 1, "GHz": 2.0, "Power": 10}, # 2.0 GHz, 10W
    {"id": 2, "GHz": 3.0, "Power": 15}, # 3.0 GHz, 15W
    {"id": 3, "GHz": 1.5, "Power": 7.5} # 1.5 GHz, 7.5W
]

# Action space for the RL Agent (AIDWECS)
ACTIONS = [
    {"w_time": 0.8, "w_energy": 0.2}, # Strongly prioritize time/deadline
    {"w_time": 0.6, "w_energy": 0.4}, # Prioritize time
    {"w_time": 0.4, "w_energy": 0.6}, # Prioritize energy
    {"w_time": 0.2, "w_energy": 0.8}, # Strongly prioritize energy
]

# Global Q-table for the AIDWECS agent
Q_TABLE = {}

# ----------------- 2. TASK & STATE MANAGEMENT -----------------

def generate_random_tasks(num_tasks: int = 10) -> List[Dict]:
    """
    Generates a batch of random tasks.
    Includes 'arrival_time' for FCFS comparison.
    """
    tasks = []
    current_time = 0
    for i in range(num_tasks):
        load = random.choice([2e9, 4e9, 6e9, 8e9, 10e9])
        deadline_offset = random.randint(4000, 10000)
        arrival_time = current_time
        tasks.append({
            "id": i + 1,
            "load": load,
            "deadline": arrival_time + deadline_offset,
            "arrival_time": arrival_time
        })
        current_time += random.randint(100, 500)
    return tasks

def discretize_state(tasks: List[Dict]) -> Tuple[int, int]:
    """
    Discretizes the system state into (Urgency_Bin, Load_Bin).
    """
    if not tasks:
        return (0, 0)

    total_tasks = len(tasks)
    avg_deadline = sum(t["deadline"] - t["arrival_time"] for t in tasks) / total_tasks
    avg_load = sum(t["load"] for t in tasks) / total_tasks

    Urgency_Bin = 1 if avg_deadline < 6500 else 0
    Load_Bin = min(2, int(avg_load // 3.5e9))

    return (Urgency_Bin, Load_Bin)

# ----------------- 3. SCHEDULER IMPLEMENTATIONS -----------------

def base_scheduler(tasks: List[Dict], weights: Dict = None, log_output: bool = False) -> Tuple:
    """
    A generic scheduling engine. It assigns tasks to the best server based on a cost function.
    If no weights are provided, it defaults to picking the server that finishes the task earliest.
    """
    server_finish_times = {s["id"]: 0 for s in SERVERS}
    total_energy = 0
    completed = 0
    logs = []

    max_exec_time = 1
    max_energy = 1
    if weights and tasks:
        max_exec_time = max(t["load"] / (s["GHz"] * 1e9) * 1000 for t in tasks for s in SERVERS)
        max_energy = max((t["load"] / (s["GHz"] * 1e9)) * s["Power"] for t in tasks for s in SERVERS)
        if max_energy == 0: max_energy = 1

    for t in tasks:
        best_cost = float("inf")
        best_server = None
        best_details = {}

        for s in SERVERS:
            exec_time_ms = t["load"] / (s["GHz"] * 1e9) * 1000
            energy_J = (exec_time_ms / 1000) * s["Power"]

            available_at = max(server_finish_times[s["id"]], t['arrival_time'])
            finish_time = available_at + exec_time_ms

            cost = finish_time

            if weights:
                norm_time = finish_time / (available_at + max_exec_time) if (available_at + max_exec_time) > 0 else 0
                norm_energy = energy_J / max_energy
                cost = weights["w_time"] * norm_time + weights["w_energy"] * norm_energy

            if cost < best_cost:
                best_cost = cost
                best_server = s
                best_details = {"finish_time": finish_time, "exec_time": exec_time_ms, "energy": energy_J}

        if best_server:
            server_finish_times[best_server["id"]] = best_details["finish_time"]
            total_energy += best_details["energy"]

            status = "✔" if best_details["finish_time"] <= t["deadline"] else "✘"
            if status == "✔": completed += 1

            if log_output:
                logs.append((t["id"], best_server["id"], round(best_details["exec_time"], 2),
                             round(best_details["energy"], 4), status,
                             round(best_details["finish_time"], 2), t["deadline"]))

    completion_rate = completed / len(tasks) if tasks else 0
    return completion_rate, total_energy, completed, logs

# --- Specific Implementations for each Scheduling Algorithm ---

def schedule_fcfs(tasks, log_output=False):
    """First-Come, First-Served"""
    sorted_tasks = sorted(tasks, key=lambda x: x['arrival_time'])
    return base_scheduler(sorted_tasks, log_output=log_output)

def schedule_sjf(tasks, log_output=False):
    """Shortest Job First"""
    sorted_tasks = sorted(tasks, key=lambda x: x['load'])
    return base_scheduler(sorted_tasks, log_output=log_output)

def schedule_edf(tasks, log_output=False):
    """Earliest Deadline First"""
    sorted_tasks = sorted(tasks, key=lambda x: x['deadline'])
    return base_scheduler(sorted_tasks, log_output=log_output)

def schedule_dwecs(tasks, log_output=False):
    """DWECS with Static, Balanced Weights"""
    sorted_tasks = sorted(tasks, key=lambda x: x['deadline'])
    static_weights = {"w_time": 0.5, "w_energy": 0.5}
    return base_scheduler(sorted_tasks, weights=static_weights, log_output=log_output)

def schedule_aidwecs(tasks, weights, log_output=False):
    """AI-Driven DWECS with Learned Weights"""
    sorted_tasks = sorted(tasks, key=lambda x: x['deadline'])
    return base_scheduler(sorted_tasks, weights=weights, log_output=log_output)


# ----------------- 4. AIDWECS TRAINING -----------------

def train_aidwecs_agent(episodes: int = 20000):
    """Training loop for the AI-Driven Scheduler (AIDWECS)."""
    LR = 0.1
    GAMMA = 0.9

    print(f"Training AIDWECS agent for {episodes} episodes...")
    for episode in range(episodes):
        tasks = generate_random_tasks()
        state = discretize_state(tasks)

        if state not in Q_TABLE:
            Q_TABLE[state] = np.zeros(len(ACTIONS))

        epsilon = max(0.05, 1.0 - episode / (episodes * 0.8))
        if random.random() < epsilon:
            action_index = random.randint(0, len(ACTIONS) - 1)
        else:
            action_index = np.argmax(Q_TABLE[state])

        action_weights = ACTIONS[action_index]
        _, energy, completed_tasks, _ = schedule_aidwecs(tasks, action_weights)

        # --- **UPDATED REWARD FUNCTION** ---
        # Heavy penalty for each failed task to prioritize completion rate
        failed_tasks = len(tasks) - completed_tasks
        reward = (completed_tasks * 10) + (failed_tasks * -25) - (energy * 0.01)

        old_value = Q_TABLE[state][action_index]
        next_max = np.max(Q_TABLE[state])
        new_value = old_value + LR * (reward + GAMMA * next_max - old_value)
        Q_TABLE[state][action_index] = new_value

        if (episode + 1) % 5000 == 0:
            print(f"  Episode {episode+1}/{episodes} completed.")

    print("Training Complete.\n")

# ----------------- 5. EVALUATION AND VISUALIZATION -----------------

def evaluate_all_schedulers(test_tasks: List[Dict]):
    """
    Evaluates all schedulers on the same set of test tasks and visualizes results.
    """
    print("----- Evaluating Schedulers on a Fixed Set of Tasks -----")

    state = discretize_state(test_tasks)
    if state not in Q_TABLE:
        print("Test state not seen during training, defaulting to balanced action.")
        action_index = 1
    else:
        action_index = np.argmax(Q_TABLE[state])

    chosen_weights = ACTIONS[action_index]
    print(f"AIDWECS Optimal Action for this state: {chosen_weights}")

    schedulers = {
        "FCFS": schedule_fcfs, "SJF": schedule_sjf, "EDF": schedule_edf,
        "DWECS (Static)": schedule_dwecs,
        "AIDWECS (Ours)": lambda tasks, log_output: schedule_aidwecs(tasks, chosen_weights, log_output)
    }

    results = []
    for name, func in schedulers.items():
        start_time = time.perf_counter()
        rate, energy, _, logs = func(test_tasks, log_output=(name == "AIDWECS (Ours)"))
        cost_ms = (time.perf_counter() - start_time) * 1000

        results.append({
            "Scheduler": name, "Task Completion (%)": rate * 100,
            "Total Energy (J)": energy, "Computational Cost (ms)": cost_ms
        })

        if name == "AIDWECS (Ours)" and logs:
            print("\n--- Detailed Log for AIDWECS ---")
            print(pd.DataFrame(logs, columns=["Task", "Server", "Exec Time", "Energy", "Status", "Finish", "Deadline"]).to_markdown(index=False))


    results_df = pd.DataFrame(results).sort_values(by="Task Completion (%)", ascending=False)
    print("\n\n--- Comparison Summary ---")
    print(results_df.to_markdown(index=False))

    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle('Performance Comparison of Scheduling Algorithms', fontsize=16, fontweight='bold')
    sns.set_style("whitegrid")

    sns.barplot(x="Scheduler", y="Task Completion (%)", data=results_df, ax=axes[0], palette="viridis").set_title('Task Completion Rate', fontsize=14)
    axes[0].tick_params(axis='x', rotation=45)

    sns.barplot(x="Scheduler", y="Total Energy (J)", data=results_df.sort_values("Total Energy (J)"), ax=axes[1], palette="plasma").set_title('Total Energy Consumption', fontsize=14)
    axes[1].tick_params(axis='x', rotation=45)

    sns.barplot(x="Scheduler", y="Computational Cost (ms)", data=results_df.sort_values("Computational Cost (ms)"), ax=axes[2], palette="magma").set_title('Scheduler Computational Cost', fontsize=14)
    axes[2].tick_params(axis='x', rotation=45)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

# --- EXECUTION ---
# 1. Train the improved AI agent
train_aidwecs_agent(episodes=20000)

# 2. Generate a final, fixed batch of tasks for a fair comparison
final_test_tasks = generate_random_tasks(num_tasks=10)
print("\n--- Generated Test Tasks ---")
print(pd.DataFrame(final_test_tasks)[['id', 'load', 'arrival_time', 'deadline']].to_markdown(index=False))

# 3. Evaluate and compare all models
evaluate_all_schedulers(final_test_tasks)

import numpy as np
import random
import pandas as pd
import time
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List, Dict, Tuple

# ----------------- 1. ENVIRONMENT & MODEL DEFINITIONS -----------------

# Heterogeneous Edge Servers (Realistic Setup)
SERVERS = [
    {"id": 1, "GHz": 2.0, "Power": 10}, # 2.0 GHz, 10W
    {"id": 2, "GHz": 3.0, "Power": 15}, # 3.0 GHz, 15W
    {"id": 3, "GHz": 1.5, "Power": 7.5} # 1.5 GHz, 7.5W
]

# Action space for the RL Agent (AIDWECS)
ACTIONS = [
    {"w_time": 0.8, "w_energy": 0.2}, # Strongly prioritize time/deadline
    {"w_time": 0.6, "w_energy": 0.4}, # Prioritize time
    {"w_time": 0.4, "w_energy": 0.6}, # Prioritize energy
    {"w_time": 0.2, "w_energy": 0.8}, # Strongly prioritize energy
]

# Global Q-table for the AIDWECS agent
Q_TABLE = {}

# ----------------- 2. TASK & STATE MANAGEMENT -----------------

def generate_random_tasks(num_tasks: int = 10) -> List[Dict]:
    """
    Generates a batch of random tasks.
    Includes 'arrival_time' for FCFS comparison.
    """
    tasks = []
    current_time = 0
    for i in range(num_tasks):
        load = random.choice([2e9, 4e9, 6e9, 8e9, 10e9])
        deadline_offset = random.randint(4000, 10000)
        arrival_time = current_time
        tasks.append({
            "id": i + 1,
            "load": load,
            "deadline": arrival_time + deadline_offset,
            "arrival_time": arrival_time
        })
        current_time += random.randint(100, 500)
    return tasks

def discretize_state(tasks: List[Dict]) -> Tuple[int, int]:
    """
    Discretizes the system state into (Urgency_Bin, Load_Bin).
    """
    if not tasks:
        return (0, 0)

    total_tasks = len(tasks)
    avg_deadline = sum(t["deadline"] - t["arrival_time"] for t in tasks) / total_tasks
    avg_load = sum(t["load"] for t in tasks) / total_tasks

    Urgency_Bin = 1 if avg_deadline < 6500 else 0
    Load_Bin = min(2, int(avg_load // 3.5e9))

    return (Urgency_Bin, Load_Bin)

# ----------------- 3. SCHEDULER IMPLEMENTATIONS -----------------

def base_scheduler(tasks: List[Dict], weights: Dict = None, log_output: bool = False) -> Tuple:
    """
    A generic scheduling engine. It assigns tasks to the best server based on a cost function.
    If no weights are provided, it defaults to picking the server that finishes the task earliest.
    """
    server_finish_times = {s["id"]: 0 for s in SERVERS}
    total_energy = 0
    completed = 0
    logs = []

    max_exec_time = 1
    max_energy = 1
    if weights and tasks:
        max_exec_time = max(t["load"] / (s["GHz"] * 1e9) * 1000 for t in tasks for s in SERVERS)
        max_energy = max((t["load"] / (s["GHz"] * 1e9)) * s["Power"] for t in tasks for s in SERVERS)
        if max_energy == 0: max_energy = 1

    for t in tasks:
        best_cost = float("inf")
        best_server = None
        best_details = {}

        for s in SERVERS:
            exec_time_ms = t["load"] / (s["GHz"] * 1e9) * 1000
            energy_J = (exec_time_ms / 1000) * s["Power"]

            available_at = max(server_finish_times[s["id"]], t['arrival_time'])
            finish_time = available_at + exec_time_ms

            cost = finish_time

            if weights:
                norm_time = finish_time / (available_at + max_exec_time) if (available_at + max_exec_time) > 0 else 0
                norm_energy = energy_J / max_energy
                cost = weights["w_time"] * norm_time + weights["w_energy"] * norm_energy

            if cost < best_cost:
                best_cost = cost
                best_server = s
                best_details = {"finish_time": finish_time, "exec_time": exec_time_ms, "energy": energy_J}

        if best_server:
            server_finish_times[best_server["id"]] = best_details["finish_time"]
            total_energy += best_details["energy"]

            status = "✔" if best_details["finish_time"] <= t["deadline"] else "✘"
            if status == "✔": completed += 1

            if log_output:
                logs.append((t["id"], best_server["id"], round(best_details["exec_time"], 2),
                             round(best_details["energy"], 4), status,
                             round(best_details["finish_time"], 2), t["deadline"]))

    completion_rate = completed / len(tasks) if tasks else 0
    return completion_rate, total_energy, completed, logs

# --- Specific Implementations for each Scheduling Algorithm ---

def schedule_fcfs(tasks, log_output=False):
    """First-Come, First-Served"""
    sorted_tasks = sorted(tasks, key=lambda x: x['arrival_time'])
    return base_scheduler(sorted_tasks, log_output=log_output)

def schedule_sjf(tasks, log_output=False):
    """Shortest Job First"""
    sorted_tasks = sorted(tasks, key=lambda x: x['load'])
    return base_scheduler(sorted_tasks, log_output=log_output)

def schedule_edf(tasks, log_output=False):
    """Earliest Deadline First"""
    sorted_tasks = sorted(tasks, key=lambda x: x['deadline'])
    return base_scheduler(sorted_tasks, log_output=log_output)

def schedule_dwecs(tasks, log_output=False):
    """DWECS with Static, Balanced Weights"""
    sorted_tasks = sorted(tasks, key=lambda x: x['deadline'])
    static_weights = {"w_time": 0.5, "w_energy": 0.5}
    return base_scheduler(sorted_tasks, weights=static_weights, log_output=log_output)

def schedule_aidwecs(tasks, weights, log_output=False):
    """AI-Driven DWECS with Learned Weights"""
    sorted_tasks = sorted(tasks, key=lambda x: x['deadline'])
    return base_scheduler(sorted_tasks, weights=weights, log_output=log_output)


# ----------------- 4. AIDWECS TRAINING -----------------

def train_aidwecs_agent(episodes: int = 20000):
    """Training loop for the AI-Driven Scheduler (AIDWECS)."""
    LR = 0.1
    GAMMA = 0.9

    print(f"Training AIDWECS agent for {episodes} episodes...")
    for episode in range(episodes):
        tasks = generate_random_tasks()
        state = discretize_state(tasks)

        if state not in Q_TABLE:
            Q_TABLE[state] = np.zeros(len(ACTIONS))

        epsilon = max(0.05, 1.0 - episode / (episodes * 0.8))
        if random.random() < epsilon:
            action_index = random.randint(0, len(ACTIONS) - 1)
        else:
            action_index = np.argmax(Q_TABLE[state])

        action_weights = ACTIONS[action_index]
        _, energy, completed_tasks, _ = schedule_aidwecs(tasks, action_weights)

        # Updated reward function with heavy penalty for failed tasks
        failed_tasks = len(tasks) - completed_tasks
        reward = (completed_tasks * 10) + (failed_tasks * -25) - (energy * 0.01)

        old_value = Q_TABLE[state][action_index]
        next_max = np.max(Q_TABLE[state])
        new_value = old_value + LR * (reward + GAMMA * next_max - old_value)
        Q_TABLE[state][action_index] = new_value

        if (episode + 1) % 5000 == 0:
            print(f"  Episode {episode+1}/{episodes} completed.")

    print("Training Complete.\n")

# ----------------- 5. EVALUATION AND VISUALIZATION -----------------

def evaluate_all_schedulers(test_tasks: List[Dict]):
    """
    Evaluates all schedulers on the same set of test tasks and visualizes results.
    """
    print("----- Evaluating Schedulers on a Fixed Set of Tasks -----")

    state = discretize_state(test_tasks)
    if state not in Q_TABLE:
        print("Test state not seen during training, defaulting to balanced action.")
        action_index = 1
    else:
        action_index = np.argmax(Q_TABLE[state])

    chosen_weights = ACTIONS[action_index]
    print(f"AIDWECS Optimal Action for this state: {chosen_weights}")

    schedulers = {
        "FCFS": schedule_fcfs, "SJF": schedule_sjf, "EDF": schedule_edf,
        "DWECS (Static)": schedule_dwecs,
        "AIDWECS (Ours)": lambda tasks, log_output: schedule_aidwecs(tasks, chosen_weights, log_output=log_output)
    }

    results = []
    for name, func in schedulers.items():
        start_time = time.perf_counter()
        rate, energy, _, logs = func(test_tasks, log_output=(name == "AIDWECS (Ours)"))
        cost_ms = (time.perf_counter() - start_time) * 1000

        results.append({
            "Scheduler": name, "Task Completion (%)": rate * 100,
            "Total Energy (J)": energy, "Computational Cost (ms)": cost_ms
        })

        if name == "AIDWECS (Ours)":
            print("\n--- Detailed Log for AIDWECS ---")
            print(pd.DataFrame(logs, columns=["Task", "Server", "Exec Time", "Energy", "Status", "Finish", "Deadline"]).to_markdown(index=False))

    results_df = pd.DataFrame(results).sort_values(by="Task Completion (%)", ascending=False)
    print("\n\n--- Comparison Summary ---")
    print(results_df.to_markdown(index=False))

    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle('Performance Comparison of Scheduling Algorithms', fontsize=16, fontweight='bold')
    sns.set_style("whitegrid")

    sns.barplot(x="Scheduler", y="Task Completion (%)", data=results_df, ax=axes[0], palette="viridis").set_title('Task Completion Rate', fontsize=14)
    axes[0].tick_params(axis='x', rotation=45)

    sns.barplot(x="Scheduler", y="Total Energy (J)", data=results_df.sort_values("Total Energy (J)"), ax=axes[1], palette="plasma").set_title('Total Energy Consumption', fontsize=14)
    axes[1].tick_params(axis='x', rotation=45)

    sns.barplot(x="Scheduler", y="Computational Cost (ms)", data=results_df.sort_values("Computational Cost (ms)"), ax=axes[2], palette="magma"
    ).set_title('Scheduler Computational Cost', fontsize=14)
    axes[2].tick_params(axis='x', rotation=45)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

# --- EXECUTION ---
# 1. Train the improved AI agent
train_aidwecs_agent(episodes=20000)

# 2. Generate a final, fixed batch of tasks for a fair comparison
final_test_tasks = generate_random_tasks(num_tasks=10)
print("\n--- Generated Test Tasks ---")
print(pd.DataFrame(final_test_tasks)[['id', 'load', 'arrival_time', 'deadline']].to_markdown(index=False))

# 3. Evaluate and compare all models
evaluate_all_schedulers(final_test_tasks)

import numpy as np
import random
import pandas as pd
import time
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List, Dict, Tuple

# ----------------- 1. ENVIRONMENT & MODEL DEFINITIONS -----------------
# More powerful servers to handle tougher tasks and highlight energy differences
SERVERS = [
    {"id": 1, "GHz": 3.5, "Power": 20}, # High-Power, High-Performance
    {"id": 2, "GHz": 2.5, "Power": 12}, # Balanced
    {"id": 3, "GHz": 1.5, "Power": 7}   # Low-Power, Energy-Efficient
]

# A more nuanced action space for the agent to have finer control
ACTIONS = [
    {"w_time": 0.9, "w_energy": 0.1}, # Focus almost entirely on speed
    {"w_time": 0.7, "w_energy": 0.3}, # Prioritize speed
    {"w_time": 0.5, "w_energy": 0.5}, # Balanced approach
    {"w_time": 0.3, "w_energy": 0.7}, # Prioritize energy saving
    {"w_time": 0.1, "w_energy": 0.9}, # Focus almost entirely on energy
]

Q_TABLE = {}

# ----------------- 2. TASK & STATE MANAGEMENT -----------------

def generate_tasks(num_tasks: int = 20, batch_type: str = 'mixed') -> List[Dict]:
    """
    Generates task batches tailored to specific scenarios (mixed, urgent, low_priority).
    """
    tasks = []
    arrival_time = 0
    for i in range(num_tasks):
        load = random.choice([4e9, 6e9, 8e9, 10e9, 12e9])

        if batch_type == 'urgent':
            # Tight deadlines (2-5 seconds)
            deadline_offset = random.randint(2000, 5000)
        elif batch_type == 'low_priority':
            # Very relaxed deadlines (10-20 seconds)
            deadline_offset = random.randint(10000, 20000)
        else: # mixed
            deadline_offset = random.randint(4000, 12000)

        tasks.append({
            "id": i + 1, "load": load,
            "deadline": arrival_time + deadline_offset,
            "arrival_time": arrival_time
        })
        arrival_time += random.randint(100, 300) # Tasks arrive quickly
    return tasks

def discretize_state(tasks: List[Dict]) -> Tuple[int, int]:
    if not tasks: return (0, 0)
    avg_urgency = sum((t['deadline'] - t['arrival_time']) for t in tasks) / len(tasks)
    avg_load = sum(t['load'] for t in tasks) / len(tasks)
    # State 0: Low urgency, State 1: High urgency
    urgency_bin = 1 if avg_urgency < 7000 else 0
    # State 0: Low load, State 1: Medium load, State 2: High load
    load_bin = min(2, int(avg_load // 4e9))
    return (urgency_bin, load_bin)

# ----------------- 3. ENHANCED SCHEDULING ENGINE -----------------

def enhanced_scheduler(tasks: List[Dict], weights: Dict = None) -> Dict:
    """
    A powerful scheduling engine that calculates multiple performance metrics.
    """
    server_finish_times = {s["id"]: 0.0 for s in SERVERS}
    server_tasks_count = {s["id"]: 0 for s in SERVERS}
    total_energy = 0.0
    completed_count = 0
    total_tardiness = 0.0
    failed_tasks_count = 0

    max_exec_time, max_energy = 1, 1
    if weights and tasks:
        max_exec_time = max(t["load"] / (s["GHz"] * 1e9) * 1000 for t in tasks for s in SERVERS)
        max_energy = max((t["load"] / (s["GHz"] * 1e9)) * s["Power"] for t in tasks for s in SERVERS)

    for t in tasks:
        best_cost, best_server, best_details = float("inf"), None, {}
        for s in SERVERS:
            exec_time_ms = t["load"] / (s["GHz"] * 1e9) * 1000
            energy_J = (exec_time_ms / 1000) * s["Power"]
            available_at = max(server_finish_times[s["id"]], t['arrival_time'])
            finish_time = available_at + exec_time_ms

            cost = finish_time
            if weights:
                norm_time = finish_time / (available_at + max_exec_time) if (available_at + max_exec_time) else 0
                norm_energy = energy_J / max_energy if max_energy else 0
                cost = weights["w_time"] * norm_time + weights["w_energy"] * norm_energy

            if cost < best_cost:
                best_cost, best_server = cost, s
                best_details = {"finish": finish_time, "energy": energy_J}

        if best_server:
            server_finish_times[best_server["id"]] = best_details["finish"]
            server_tasks_count[best_server["id"]] += 1
            total_energy += best_details["energy"]

            if best_details["finish"] <= t["deadline"]:
                completed_count += 1
            else:
                failed_tasks_count += 1
                total_tardiness += (best_details["finish"] - t["deadline"])

    # --- Calculate Final Metrics ---
    total_runtime = max(server_finish_times.values())
    total_busy_time = sum(server_finish_times.values())

    return {
        "Completion Rate (%)": (completed_count / len(tasks)) * 100 if tasks else 0,
        "Total Energy (J)": total_energy,
        "Avg Tardiness (ms)": (total_tardiness / failed_tasks_count) if failed_tasks_count > 0 else 0,
        "Tasks per Joule": completed_count / total_energy if total_energy > 0 else 0,
        "Avg Utilization (%)": (total_busy_time / (len(SERVERS) * total_runtime)) * 100 if total_runtime > 0 else 0,
        "Server Tasks Count": server_tasks_count
    }

# --- Wrapper functions for each algorithm ---
def run_fcfs(tasks):
    return enhanced_scheduler(sorted(tasks, key=lambda x: x['arrival_time']))
def run_sjf(tasks):
    return enhanced_scheduler(sorted(tasks, key=lambda x: x['load']))
def run_edf(tasks):
    return enhanced_scheduler(sorted(tasks, key=lambda x: x['deadline']))
def run_dwecs(tasks):
    return enhanced_scheduler(sorted(tasks, key=lambda x: x['deadline']), weights={"w_time": 0.5, "w_energy": 0.5})
def run_aidwecs(tasks, weights):
    return enhanced_scheduler(sorted(tasks, key=lambda x: x['deadline']), weights=weights)

# ----------------- 4. AI AGENT TRAINING -----------------
def train_aidwecs_agent(episodes: int = 30000):
    LR, GAMMA = 0.1, 0.9
    print(f"Training AIDWECS agent for {episodes} episodes...")
    for episode in range(episodes):
        batch_type = random.choice(['mixed', 'urgent', 'low_priority'])
        tasks = generate_tasks(batch_type=batch_type)
        state = discretize_state(tasks)
        if state not in Q_TABLE: Q_TABLE[state] = np.zeros(len(ACTIONS))

        epsilon = max(0.05, 1.0 - episode / (episodes * 0.8))
        action_idx = random.randint(0, len(ACTIONS) - 1) if random.random() < epsilon else np.argmax(Q_TABLE[state])

        results = run_aidwecs(tasks, ACTIONS[action_idx])

        # **NEW REWARD**: A combined score that balances completion and energy
        # The goal is to maximize this score.
        completion_score = results["Completion Rate (%)"]
        energy_penalty = results["Total Energy (J)"] / 50 # Tuned penalty
        reward = completion_score - energy_penalty

        old_val = Q_TABLE[state][action_idx]
        next_max = np.max(Q_TABLE[state])
        Q_TABLE[state][action_idx] = old_val + LR * (reward + GAMMA * next_max - old_val)
    print("Training Complete.\n")

# ----------------- 5. COMPREHENSIVE EVALUATION & VISUALIZATION -----------------
def run_comprehensive_evaluation(batch_type: str):
    print(f"\n{'═'*80}\n📊 EVALUATION SCENARIO: {batch_type.upper()} WORKLOAD 📊\n{'═'*80}")

    test_tasks = generate_tasks(num_tasks=20, batch_type=batch_type)
    state = discretize_state(test_tasks)

    chosen_weights = ACTIONS[np.argmax(Q_TABLE[state])] if state in Q_TABLE else ACTIONS[2]
    print(f"AIDWECS has chosen its strategy for this scenario: {chosen_weights}\n")

    schedulers = {
        "FCFS": run_fcfs, "SJF": run_sjf, "EDF": run_edf,
        "DWECS (Static)": run_dwecs,
        "AIDWECS (Ours)": lambda tasks: run_aidwecs(tasks, chosen_weights)
    }

    all_results, server_allocations = [], {}
    for name, func in schedulers.items():
        start_time = time.perf_counter()
        results = func(test_tasks)
        results["Computational Cost (ms)"] = (time.perf_counter() - start_time) * 1000

        # Calculate the final balanced score
        results["Combined Score"] = results["Completion Rate (%)"] - (results["Total Energy (J)"] / 50)

        results["Scheduler"] = name
        all_results.append(results)
        server_allocations[name] = results.pop("Server Tasks Count")

    # --- Generate Tables ---
    results_df = pd.DataFrame(all_results).set_index("Scheduler")

    print("\n--- TABLE 1: Core Performance Metrics ---")
    core_metrics = ["Completion Rate (%)", "Total Energy (J)", "Combined Score"]
    print(results_df[core_metrics].sort_values("Combined Score", ascending=False).to_markdown())

    print("\n--- TABLE 2: Efficiency & Failure Analysis ---")
    efficiency_metrics = ["Avg Tardiness (ms)", "Tasks per Joule", "Avg Utilization (%)", "Computational Cost (ms)"]
    print(results_df[efficiency_metrics].sort_values("Tasks per Joule", ascending=False).to_markdown())

    # --- Generate Graphs ---
    metrics_to_plot = ["Completion Rate (%)", "Total Energy (J)", "Combined Score", "Avg Tardiness (ms)", "Tasks per Joule"]
    fig, axes = plt.subplots(len(metrics_to_plot), 1, figsize=(12, 20))
    fig.suptitle(f'Comparison on {batch_type.upper()} Workload', fontsize=18, fontweight='bold')

    for i, metric in enumerate(metrics_to_plot):
        df_sorted = results_df.sort_values(metric, ascending='Total Energy (J)' in metric or 'Tardiness' in metric)
        sns.barplot(x=df_sorted.index, y=df_sorted[metric], ax=axes[i], palette='viridis')
        axes[i].set_title(metric, fontsize=14)
        axes[i].set_xlabel('')
    plt.tight_layout(rect=[0, 0.03, 1, 0.96])
    plt.show()

    # Server Allocation Visualization
    allocation_df = pd.DataFrame(server_allocations).T
    allocation_df.plot(kind='bar', stacked=True, figsize=(12, 6), colormap='plasma')
    plt.title(f'Server Task Allocation ({batch_type.upper()} Workload)', fontsize=16)
    plt.ylabel('Number of Tasks Assigned')
    plt.xticks(rotation=45)
    plt.legend(title='Server ID')
    plt.show()

# --- MAIN EXECUTION ---
train_aidwecs_agent()
run_comprehensive_evaluation(batch_type='mixed')
run_comprehensive_evaluation(batch_type='urgent')
run_comprehensive_evaluation(batch_type='low_priority')

import numpy as np
import random
import pandas as pd
import time
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List, Dict, Tuple

# ----------------- 1. ENVIRONMENT & MODEL DEFINITIONS -----------------
SERVERS = [
    {"id": 1, "GHz": 3.5, "Power": 20}, # High-Power, High-Performance
    {"id": 2, "GHz": 2.5, "Power": 12}, # Balanced
    {"id": 3, "GHz": 1.5, "Power": 7}   # Low-Power, Energy-Efficient
]

ACTIONS = [
    {"w_time": 0.9, "w_energy": 0.1}, {"w_time": 0.7, "w_energy": 0.3},
    {"w_time": 0.5, "w_energy": 0.5}, {"w_time": 0.3, "w_energy": 0.7},
    {"w_time": 0.1, "w_energy": 0.9}
]

Q_TABLE = {}

# ----------------- 2. TASK & STATE MANAGEMENT -----------------

def generate_low_stress_tasks(num_tasks: int = 15) -> List[Dict]:
    """
    Generates a batch of tasks with relaxed deadlines to ensure all schedulers
    can achieve a 100% completion rate, isolating energy as the key variable.
    """
    tasks = []
    arrival_time = 0
    for i in range(num_tasks):
        load = random.choice([2e9, 4e9, 6e9]) # Lighter loads
        # Very relaxed deadlines (15-25 seconds)
        deadline_offset = random.randint(15000, 25000)
        tasks.append({
            "id": i + 1, "load": load,
            "deadline": arrival_time + deadline_offset,
            "arrival_time": arrival_time
        })
        arrival_time += random.randint(200, 500)
    return tasks

def discretize_state(tasks: List[Dict]) -> Tuple[int, int]:
    if not tasks: return (0, 0)
    avg_urgency = sum((t['deadline'] - t['arrival_time']) for t in tasks) / len(tasks)
    # For this experiment, urgency will always be low (0)
    urgency_bin = 1 if avg_urgency < 10000 else 0
    return (urgency_bin,) # State is now simpler, just based on urgency

# ----------------- 3. SCHEDULING ENGINE -----------------

def scheduling_engine(tasks: List[Dict], weights: Dict = None) -> Dict:
    server_finish_times = {s["id"]: 0.0 for s in SERVERS}
    server_tasks_count = {s["id"]: 0 for s in SERVERS}
    total_energy = 0.0
    completed_count = 0

    max_exec_time, max_energy = 1, 1
    if weights and tasks:
        max_exec_time = max(t["load"] / (s["GHz"] * 1e9) * 1000 for t in tasks for s in SERVERS)
        max_energy = max((t["load"] / (s["GHz"] * 1e9)) * s["Power"] for t in tasks for s in SERVERS)

    for t in tasks:
        best_cost, best_server, best_details = float("inf"), None, {}
        for s in SERVERS:
            exec_time_ms = t["load"] / (s["GHz"] * 1e9) * 1000
            energy_J = (exec_time_ms / 1000) * s["Power"]
            available_at = max(server_finish_times[s["id"]], t['arrival_time'])
            finish_time = available_at + exec_time_ms

            cost = finish_time # Default for EDF, FCFS, etc.
            if weights: # For DWECS and AIDWECS
                norm_time = finish_time / (available_at + max_exec_time) if (available_at + max_exec_time) > 0 else 0
                norm_energy = energy_J / max_energy if max_energy > 0 else 0
                cost = weights["w_time"] * norm_time + weights["w_energy"] * norm_energy

            if cost < best_cost:
                best_cost, best_server = cost, s
                best_details = {"finish": finish_time, "energy": energy_J}

        if best_server:
            server_finish_times[best_server["id"]] = best_details["finish"]
            server_tasks_count[best_server["id"]] += 1
            total_energy += best_details["energy"]
            if best_details["finish"] <= t["deadline"]:
                completed_count += 1

    return {
        "Completion Rate (%)": (completed_count / len(tasks)) * 100 if tasks else 0,
        "Total Energy (J)": total_energy,
        "Server Allocation": server_tasks_count
    }

# --- Wrapper functions for each algorithm ---
def run_edf(tasks): return scheduling_engine(sorted(tasks, key=lambda x: x['deadline']))
def run_dwecs(tasks): return scheduling_engine(sorted(tasks, key=lambda x: x['deadline']), weights={"w_time": 0.5, "w_energy": 0.5})
def run_aidwecs(tasks, weights): return scheduling_engine(sorted(tasks, key=lambda x: x['deadline']), weights=weights)

# ----------------- 4. AI AGENT TRAINING -----------------
def train_aidwecs_agent(episodes: int = 10000):
    LR, GAMMA = 0.1, 0.9
    print(f"Training AIDWECS agent for {episodes} episodes...")
    for episode in range(episodes):
        # Training on low-stress tasks to learn energy conservation
        tasks = generate_low_stress_tasks()
        state = discretize_state(tasks)
        if state not in Q_TABLE: Q_TABLE[state] = np.zeros(len(ACTIONS))

        epsilon = max(0.05, 1.0 - episode / (episodes * 0.8))
        action_idx = random.randint(0, len(ACTIONS) - 1) if random.random() < epsilon else np.argmax(Q_TABLE[state])

        results = run_aidwecs(tasks, ACTIONS[action_idx])

        # Reward function: maximize completion, minimize energy.
        # Since completion will be 100, this becomes a pure energy minimization problem.
        reward = results["Completion Rate (%)"] - (results["Total Energy (J)"] / 10)

        old_val = Q_TABLE[state][action_idx]
        next_max = np.max(Q_TABLE[state])
        Q_TABLE[state][action_idx] = old_val + LR * (reward + GAMMA * next_max - old_val)
    print("Training Complete.\n")

# ----------------- 5. FOCUSED EVALUATION & VISUALIZATION -----------------
def run_focused_evaluation():
    print(f"\n{'═'*80}\n⚡ FOCUSED EVALUATION: ENERGY EFFICIENCY UNDER 100% COMPLETION ⚡\n{'═'*80}")

    test_tasks = generate_low_stress_tasks(num_tasks=20)
    state = discretize_state(test_tasks)

    chosen_weights = ACTIONS[np.argmax(Q_TABLE[state])] if state in Q_TABLE else ACTIONS[4] # Default to energy saving
    print(f"AIDWECS Policy for this scenario: {chosen_weights}\nThis shows it has learned to prioritize energy savings.\n")

    schedulers = {
        "EDF": run_edf,
        "DWECS (Static)": run_dwecs,
        "AIDWECS (Ours)": lambda tasks: run_aidwecs(tasks, chosen_weights)
    }

    all_results = []
    for name, func in schedulers.items():
        results = func(test_tasks)
        results["Scheduler"] = name
        all_results.append(results)

    # --- Generate Final Table & Graphs ---
    results_df = pd.DataFrame(all_results)

    print("\n--- Final Comparison Table ---")
    print(results_df[['Scheduler', 'Completion Rate (%)', 'Total Energy (J)']].sort_values("Total Energy (J)").to_markdown(index=False))

    # --- Main Energy Comparison Graph ---
    fig, ax1 = plt.subplots(1, 1, figsize=(10, 6))
    sns.barplot(x="Scheduler", y="Total Energy (J)", data=results_df.sort_values("Total Energy (J)"), ax=ax1, palette='plasma')
    ax1.set_title('Energy Consumption Comparison (at 100% Task Completion)', fontsize=16, fontweight='bold')
    ax1.set_xlabel('Scheduler', fontsize=12)
    ax1.set_ylabel('Total Energy Consumed (J)', fontsize=12)
    plt.show()

    # --- Server Allocation Graph (to explain the 'why') ---
    allocation_data = results_df.set_index('Scheduler')['Server Allocation'].apply(pd.Series)
    allocation_data.plot(kind='bar', stacked=True, figsize=(12, 7), colormap='viridis')
    plt.title('Server Task Allocation', fontsize=16, fontweight='bold')
    plt.xlabel('Scheduler', fontsize=12)
    plt.ylabel('Number of Tasks Assigned to Each Server')
    plt.xticks(rotation=0)
    plt.legend(title=f'Server ID (1={SERVERS[0]["Power"]}W, 2={SERVERS[1]["Power"]}W, 3={SERVERS[2]["Power"]}W)')
    plt.show()


# --- MAIN EXECUTION ---
train_aidwecs_agent()
run_focused_evaluation()

